import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/lib/providers/minikit-provider";
import Main from "@/components/Main";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="notranslate dark">
      <MiniKitProvider>
        <body
          className={cn(`h-svh bg-background antialiased`)}
          suppressHydrationWarning
        >
          <div className="sticky top-0 z-50 flex w-full items-center justify-between bg-muted p-2 pl-4 h-14">
            <p className={"text-lg font-semibold"}>Argiefy</p>
          </div>

          <Main>{children}</Main>
        </body>
      </MiniKitProvider>
    </html>
  );
}
