import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/lib/providers/minikit-provider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const MinikitProvider = dynamic(() => import("@/lib/providers/minikit-provider"), { ssr: false });

  return (
    <html lang="en">
      <MinikitProvider>
        <body className={inter.className}>{children}</body>
      </MinikitProvider>
    </html>
  );
}
